/* Requires the Docker Pipeline plugin */
pipeline {
    agent { docker { image 'golang:1.23.0-alpine3.20' } }
    stages {
        stage('build') {
            steps {
                sh 'go version'
            }
        }
         stage('k6') {
            agent {
                docker {
                    image 'grafana/k6'
                    args '--entrypoint=""'
                    reuseNode true
                }
            }
            steps {
                sh 'k6 run script.js --quiet'
            }
        }
}
}