pipeline {

    agent { dockerfile true }

    stages {
        stage('prepare'){
            steps{
                sh 'make deps'
            }
        }
        stage('Tests'){
            parallel{
                stage('functional Tests') {
            steps {
                    sh 'make run-functional-tests'
            }
        }
        stage('performance Tests') {
            steps {
                    sh 'make run-k6-smoke-test'
            }
        }
            }
    }
}
